### DISCUSSION TITLE
Running into dependency error when trying to self host

### DISCUSSION THREAD

**Discussion by SleeplessOne1917** [samcf/ogres#153] [Q&A] [answered]
I'm following the wiki trying to self host this and am running into an error. When I run `sudo docker compose up -d`, I get this error:

```
 => ERROR [frontend node 5/5] RUN npm install                                                 1.5s
------
 > [frontend node 5/5] RUN npm install:
1.113 npm error code ERESOLVE
1.113 npm error ERESOLVE could not resolve
1.113 npm error
1.113 npm error While resolving: @dnd-kit/core@6.0.8
1.113 npm error Found: react@19.0.0-rc-512b09b2-20240718
1.113 npm error node_modules/react
1.113 npm error   react@"^19.0.0-rc-512b09b2-20240718" from the root project
1.113 npm error   peer react@"19.0.0-rc-512b09b2-20240718" from react-dom@19.0.0-rc-512b09b2-20240718
1.113 npm error   node_modules/react-dom
1.113 npm error     react-dom@"^19.0.0-rc-512b09b2-20240718" from the root project
1.113 npm error
1.113 npm error Could not resolve dependency:
1.113 npm error peer react@">=16.8.0" from @dnd-kit/core@6.0.8
1.113 npm error node_modules/@dnd-kit/core
1.113 npm error   @dnd-kit/core@"^6.0.8" from the root project
1.113 npm error
1.113 npm error Conflicting peer dependency: react@18.3.1
1.113 npm error node_modules/react
1.113 npm error   peer react@">=16.8.0" from @dnd-kit/core@6.0.8
1.113 npm error   node_modules/@dnd-kit/core
1.113 npm error     @dnd-kit/core@"^6.0.8" from the root project
1.113 npm error
1.113 npm error Fix the upstream dependency conflict, or retry
1.113 npm error this command with --force or --legacy-peer-deps
1.113 npm error to accept an incorrect (and potentially broken) dependency resolution.
1.113 npm error
1.113 npm error
1.113 npm error For a full report see:
1.113 npm error /root/.npm/_logs/2024-08-06T19_57_29_691Z-eresolve-report.txt
1.114 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-08-06T19_57_29_691Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
```

Steps I followed:
1. Cloned repo into `/etc/ogres` on my server
2. Installed `nodejs` (version 20.16.0), and `clojure` (1.11.1-2) - npm was automatically installed when installing `nodejs`
3. Edited `docker-compose.yaml` with changes:
- Changed frontend service `VERSION` arg to "latest"
- Changed frontend service `SERVER_SOCKER_URL` arg to "ws::/<my production domain here>/ws
- Commented out `ports`, `develop`, and `watch` sections of frontend service
- Changed nginx service `VERSION` arg to "latest"
- Changed nginx service ports from 8080:80 to 3322:80
4. Ran `docker compose up -d`
5. Got error that was printed above

Some machine info:
OS: Debian GNU/Linux bookworm 12.6 x86_64

docker-compose.yaml

```yaml
services:
  frontend:
    build:
      context: .
      dockerfile: ./deploy/frontend.dockerfile
      args:
        # The release tag for the client build (by default the client uses `latest`).
        # - For a different build, supply the following param: `/play?r={VERSION}`.
        VERSION: "latest"
        # Mode must be either "release" (for production) or "watch" (for development)
        MODE: "release"
        # The URL that will be accessed by the user's browser
        # - When running in production, you likely want to use `wss://{YOUR_DOMAIN}/ws`
        SERVER_SOCKET_URL: "ws://tabletop.databunker.monster/ws"
    volumes:
      - frontend:/build
        #ports:
      # Port used for hot reloading in shadow-cljs's watch mode
      #- "9630:9630"
      #develop:
      #watch:
      #  - action: sync
      #    path: ./src/main/ogres/app
      #    target: /build/src/main/ogres/app
      #  - action: rebuild
      #    path: package.json

  backend:
    build:
      context: .
      dockerfile: ./deploy/backend.dockerfile
    expose:
    # The websocket connection exposed by the server
    - "8090"

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx.dockerfile
      args:
        VERSION: "latest"
        # The URL to the server's websocket, which will be proxied by nginx
        SERVER_SOCKET_URL: "http://backend:8090/ws"
    volumes:
        - ./deploy/docker-nginx.template:/etc/nginx/templates/default.conf.template:ro
        - frontend:/usr/share/nginx/app
    ports:
      - "3322:80"

volumes:
  frontend:
```

If you can tell what I'm getting wrong, please let me know.
